### ISSUE TITLE
Error 404 in Supabase when trying to login or register.

### ISSUE THREAD

**Issue by psavarmattas** [Izan2020/attendance_app#1]
FATAL EXCEPTION: main
                                                                                                    Process: com.example.aplikasi_absen, PID: 27200
                                                                                                    retrofit2.HttpException: HTTP 404 
                                                                                                    	at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:53)
                                                                                                    	at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161)
                                                                                                    	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
                                                                                                    	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@d648bfe, Dispatchers.Main.immediate]

**Comment by glantrox** [comment]
Sorry, apparently the supabase API session is expired, i've gotta renew it.
